name: CI Check
on: [push] # Chạy mỗi khi có ai đó push code lên

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check if file exists
        run: |
          ls index.html
          echo "Kiểm tra hoàn tất: File index.html tồn tại!"
